### ISSUE TITLE
Update spec to include path /wallets/:wallet_id/trust_relationships

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-wallet-api#101]
Trust relationships are no longer included in /wallets.  Don't return trust relationships for wallets that you don't either manage or have a trust relationship with.

**Comment by dadiorchen** [comment]
I am thinking maybe this is unnecessary, because actually now we can check the trust_relationships by: GET /trust_relationships?wallet=wallet_name

**Comment by deepwinter** [comment]
That sounds right.  Let's make a final decision to close this issue in the meeting this week.

**Comment by mzyau** [comment]
@dadiorchen has this GET /trust_relationships?wallet=wallet_name endpoint been built yet?
