### ISSUE TITLE
/transfers/{transfer_id}/fulfill  implicit should be false by default

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-wallet-api#103]

**Comment by dadiorchen** [comment]
@deepwinter currently, the `tokens` and `implicit` is alternative options, just need to set one of both, so we don't need to set the implicit = false I think?

**Comment by deepwinter** [comment]
posting to fulfill for a bundle transfer without tokens set should NOT trigger an implicit transfer, because there may have been operator error.  Instead implicit=true should be required to execute an implicit fulfillment, otherwise the API should return an error.  This is so a client can't accidentally trigger an implicit transfer and loose tokens they didn't mean to transfer.

**Comment by deepwinter** [comment]
If tokens not set, must be 

```
{
  "implicit": true
}
```
