### ISSUE TITLE
If a pending transfer cannot be fulfilled it becomes 'failed', or don't allow this to state to be reached.

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-wallet-api#108]
For example, if Ezra has 500 tokens and sends those tokens to two untrusted wallets (two transfers of 500), they will both be pending.  The first walled to accept gets the tokens, the 2nd one fails.

As an additional check, a wallet should not be able to create pending transfers that sum to more tokens than they have in their wallet.

**Comment by dadiorchen** [comment]
In my opinion, it's fine to leave this transfer there in state of `pending`, and warning the token is not enough, then when the sender got enough tokens, just do it again to complete this transfer, or, if the sender can not make it, just `decline` or `cancel` it?
