### ISSUE TITLE
Clean up response from GET wallets

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-wallet-api#134]
{
            "id": 1,
            "type": "p",
            "name": "Harley_OConner47",
            "email": null,
            "phone": null,
            "password": "cd020116c2b245eadf411151e361790e6300c3f6fb43d40290e02d5a59ea5218bcbad2e496e204464b7163d4f13524239cf6d80c34a01c6a7def92d8055c40e7",
            "salt": "CNhTUMszxHmCJl0",
            "logo_url": null,
            "tokens_in_wallet": 914
        }

**Comment by mzyau** [comment]
Duplicate from #145
