### ISSUE TITLE
transferring to the same wallet as originated one should return error

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-wallet-api#140]
`{
    "bundle": {
        "bundle_size": 100
    },
    "sender_wallet": "Kristina.Ullrich",
    "receiver_wallet": "Kristina.Ullrich"
}`

response:
`{
    "type": "send",
    "parameters": {
        "bundle": {
            "bundleSize": 100
        }
    },
    "state": "completed",
    "created_at": "2020-12-15T06:18:45.081Z",
    "closed_at": "2020-12-15T06:18:45.081Z",
    "active": true,
    "id": 52,
    "originating_wallet": "Kristina.Ullrich",
    "source_wallet": "Kristina.Ullrich",
    "destination_wallet": "Kristina.Ullrich"
}`

**Comment by XLPeng57** [comment]
@Kpoke Can I work on this?
