### ISSUE TITLE
Claim feature for /transfer

### ISSUE THREAD

**Issue by wm798222** [Greenstand/treetracker-wallet-api#152]
The transfer POST needs to accept a boolean for claim and store that with the transfer in the db.  The token also needs a  'claimed' boolean in the db, which should be set when the transfer completes. And if claimed is true for a token, it cannot participate in any further transfers. This boolean should also be reported by the GET tokens endpoint.

**Comment by Kpoke** [comment]
Was this completed?

**Comment by wm798222** [comment]
Hi Olojakpoke - yes I believe so.

Best,
Will
