### ISSUE TITLE
BaseRepository need to support `offset`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-api#162]
To make it's possible to write pagination for list type of endpoint.

**Comment by deepwinter** [comment]
@zo-chu can this be handled by your sweep of limit/offset?

**Comment by zo-chu** [comment]
I'm not sure, @dadiorchen do you mean to make a standalone functionality? I made `getByFilter` recognise pagination

**Comment by dadiorchen** [comment]
I think what you did is just what the issue meant, yes, to let getByFilter recognize `limit` and `offset`

**Comment by zo-chu** [comment]
great, closing then
