### ISSUE TITLE
Remove all calls to expect-runtime from the codebase.

### ISSUE THREAD

**Issue by ivorycoast** [Greenstand/treetracker-wallet-api#181]
**Explaination:**

When sending a GET request to the /tokens/{ID} URL with a wrong token ID. The server responds with an Internal Server Error (Error 500) instead of sending an HTTPError message provided in the code:

```
async getById(id){
...
   expect(result,() => new HttpError(404, `can not found token by id:${id}`))...
...
}
```

Here is the error message I got:

```
HTTP/1.1 500 Internal Server Error
...
{"code":500,"message":"Unknown error (select * from \"token\" where \"id\" = $1 limit $2 - invalid input syntax for type uuid: \"...BAD...ID...\")"}
```

**Risk:**
Database Information Disclosure

**Where is the issue?**
/repositories/TokenRepository.js

**How to fix/Recommendation:**
I recommend to review the implementation of the "expect" function to trigger the correct error message instead of the internal server error.

**Comment by dadiorchen** [comment]
Feel free to remove/replace the `expect` calling, with a library like Joi, the expect-runtime is a temporary solution for the repo.

**Comment by ivorycoast** [comment]
Ok. I am currently reviewing the code for security issues.
It will also be good to review the entire code as this issue can be found elswhere also (POST /transfer, etc.).

**Comment by deepwinter** [comment]
Remove all calls to expect runtime from the codebase.

**Comment by Kpoke** [comment]
Replace with Joi validation where applicable

**Comment by XLPeng57** [comment]
I can help with this. Could you assign it to me?
