### ISSUE TITLE
Internal Server Error when a wrong state/type/request_type is provided

### ISSUE THREAD

**Issue by ivorycoast** [Greenstand/treetracker-wallet-api#184]
**Explaination:**

When sending a GET request to the "/trust_relationships?request_type={DATA}" URL with a wrong data. The same error happens with "state=..." and "type=...". The server responds with an Internal Server Error (Error 500) instead of sending an HTTPError message.

The issue is located in "/repositories/BaseRepository.js" which is accessible from  "/repositories/TrustRepository.js" via "/models/Wallet.js":

```
async getByFilter(filter, options){
...
   const result = await promise;
...
}
```

Here is the error message I got:

```
HTTP/1.1 500 Internal Server Error
...
{"code":500,"message":"Unknown error (select * from \"wallet_trust\" where (\"request_type\" = $1 and (\"actor_wallet_id\" = $2 or \"target_wallet_id\" = $3 or \"originator_wallet_id\" = $4)) - invalid input value for enum public.entity_trust_request_type: \"DATA..HERE..\")"}
```

**Risk:**
Database Information Disclosure

**Where is the issue?**
/repositories/BaseRepository.js

**How to fix/Recommendation:**
I recommend to handle errors by providing a proper error message.

**Comment by dadiorchen** [comment]
Interesting, so the thing is: you manually added parameters in the request which isn't defined in the spec, am I correct?

**Comment by dadiorchen** [comment]
Like this parameter: state=xxx

**Comment by dadiorchen** [comment]
So we need to restrict the endpoint validation to avoid extra parameters are provided?

**Comment by ivorycoast** [comment]
Hello,

The parameter state is mentioned inside the trustRouter.js inside the "trustRouter.get('/',..." function.

You have:
```
...
      Joi.object({
        state: Joi.string(),
        type: Joi.string(),
        request_type: Joi.string(),
        start: Joi.number(),
        limit: Joi.number().min(1).max(10000).integer(),
...
    const {state, type, request_type, limit, start} = req.query;
...
```

**Comment by pranavkparti** [comment]
This issue is resolved. Invalid request parameters return a `422` error.

![image](https://github.com/Greenstand/treetracker-wallet-api/assets/15161954/8105da94-85d8-478e-bb47-8f01fc3ec33f)
