### ISSUE TITLE
Add default limit Parameter to get wallets endpoint

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-wallet-api#185]
Set wallets?limit=??? as a default value of 1000. Currently this has to be done manually. 

The default value should be the same value as the maximum.   Add metadata to the response that reports back the offset and limit used in this query, as well as the total number of wallets matching the query parameters.  This way the default for the limit parameter in the API is exposed.

**Comment by dadiorchen** [comment]
The best way to handle this problem is that the client like Postman can automatically set it up I mean the limit parameter, is there any way to make this happen? Could we provide the default value in the spec/yaml, and then Postman can recognize it and set it in the UI?

**Comment by deepwinter** [comment]
The default can be the same value as the maximum.

**Comment by deepwinter** [comment]
We should add metadata that reports back the offset and limit used in this query, so that the default for the limit parameter in the API  is exposed.

**Comment by zo-chu** [comment]
At the moment limit is a required field, we can make a default value instead but it's a different flow, then we need to return the limit somehow. Unless there is a specific use case for it, I'd suggest to keep it simple and make client set limit explicitly . 
It should be very easy using Postman

**Comment by Kpoke** [comment]
Reference: https://github.com/Greenstand/treetracker-api/blob/2e12774e45c71c9abef64b135bd339a768b5cfd5/server/handlers/captureHandler/index.js#L28-L43 , https://github.com/Greenstand/treetracker-api/blob/main/server/utils/helper.js

**Comment by WeiyuSun** [comment]
I can handle this issue; could you please assign it to me? thanks
