### ISSUE TITLE
Sweep limit, offset parameters for all endpoints

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-wallet-api#186]
The implementation of limit and offset parameters for all endpoints needs to be checked and corrected in several ways.

(1) Some endpoints have in memory limit,offset logic implemented, instead limit and offset should use the build in LIMIT and OFFSET functionalities of SQL, using knex.

(2) All endpoints should have min (0) and max (1000) parameters for limit, and a min parameter of 0 for offset.  Offset should default to 0, and limit should default to the max of 1000.

(3) Additionally the following issues need to be checked and resolved if work is still needed.

https://github.com/Greenstand/treetracker-wallet-api/issues/185
https://github.com/Greenstand/treetracker-wallet-api/issues/183
https://github.com/Greenstand/treetracker-wallet-api/issues/87

**Comment by ivorycoast** [comment]
For information, the "routes/trustRouter.js" file contains a limit from 0 to 10 000:
`limit: Joi.number().min(1).max(10000).integer()`
