### ISSUE TITLE
Shouldn't restrict the max start parameter.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-api#191]
https://github.com/Greenstand/treetracker-wallet-api/blob/807e09d275d052f43c666ec0fe8de9ebeddb8255/server/routes/tokenRouter.js#L89

https://github.com/Greenstand/treetracker-wallet-api/blob/807e09d275d052f43c666ec0fe8de9ebeddb8255/server/routes/tokenRouter.js#L46

I think we shouldn't restrict the maximum start value to 10000 right?

**Comment by deepwinter** [comment]
@zo-chu was this addressed in your sweep?

**Comment by zo-chu** [comment]
good point, this should probably always be limited by integer . I'll add a fix
