### ISSUE TITLE
Impact creator not displayed in Wallet tree token view 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-wallet-api#194]
The impact Wallet detail view needs to have the impact creator organisation. 
In most cases the planter has worked under an org. which is known and registered in the system. We should not loose that link and need to display that as a vital piece of information. 
Currently the detail view shows
Planter A
Impact Owner

**Comment by deepwinter** [comment]
Impact Producer IS included in this view, and this team does not develop the impact wallet web application.  Please direct these requests to their repository, treetracker-wallet-web
