### ISSUE TITLE
Create subwallets without restrictions

### ISSUE THREAD

**Issue by ivorycoast** [Greenstand/treetracker-wallet-api#195]
**Explaination:**

It is possible to create subwallets without characters restrictions and there is no minimum and maximum length.

The issue is located in "/routes/walletRouter.js":

```
walletRouter.post('/', 
  helper.apiKeyHandler,
  helper.verifyJWTHandler,
  helper.handlerWrapper(async (req, res, next) => {
    Joi.assert(
      req.body,
      Joi.object({
        **wallet: Joi.string().required(),**
      })
    );
...
```

After verification, it seems that you are using "character varying" in the Postgresql Database. This means that the data (the subwallet name) could go to 1GB:
https://www.postgresql.org/docs/current/datatype-character.html

**Risk:**
Missconfiguration - Increase Database storage by sending subwallets name up to 1GB (annoying)

**Where is the issue?**
/routes/walletRouter.js

**How to fix/Recommendation:**
I recommend to limit the length and also the type of characters. This could be an issue if the data is showed in a front-end application.

**Comment by WeiyuSun** [comment]
I can deal with this. Can you assign it to me?
