### ISSUE TITLE
Generate events when token is created/transferred and assigned to a wallet

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/treetracker-wallet-api#216]
Generate events when one or more tokens are created or transferred and assigned to a wallet. The generated event should be persisted in `domain_events` table in wallet schema (please see examples [here](https://github.com/Greenstand/webmap-query-service-consumer/blob/master/database/migrations/sqls/20210324202641-domain-event-up.sql)). This event should be then published to rabbit mq messaging service utilizing a wallet exchange using a persistent queue named `wallet:token-events`.
 
The format of this event is to be finalized and not yet concrete. But the idea is, captures processed and verified would have eligible tokens and these tokens are owned by or associated with wallets. 

When a creation or transfer of tokens occurs in wallet api, TokensAssigned event should be generated. The format of this event will be roughly of the following kind (concrete format will be known soon with deliberation but will be more or less the same as follows):

{
"type": "TokensAssigned",
"wallet_name": "joeswallet",
"entries": [
{ "capture_id": "63e00bca-8eb0-11eb-8dcd-0242ac130003", "token_id": "9d7abad8-8eb0-11eb-8dcd-0242ac130003" },
{ "capture_id": "8533b704-8eb0-11eb-8dcd-0242ac130003", "token_id":"a5799d94-8eb0-11eb-8dcd-0242ac130003" } ]
}

If 1000 tokens are generated or transferred and assigned to a wallet, then 10 events are generated with each entries referring to 100 capture_id and its associated token_ids thereby avoiding creating 1000 events flooding the message queue. The batch of 100 is arbitrary and we could experiment with the size.

**Comment by Kpoke** [comment]
Not sure if this should be in the wallet API. Also currently token creation is done via an airflow manual job
