### ISSUE TITLE
add logger and remove all console logs

### ISSUE THREAD

**Issue by zo-chu** [Greenstand/treetracker-wallet-api#220]
It's a good practice to have a logger with different logging levels (info, warning, error) and separate logs accordingly. This makes developing, monitoring and debugging much easier. There are some popular libs like https://github.com/winstonjs/winston 

we should also erase all console logs, so they don't create noise especially in tests.

**Comment by dadiorchen** [comment]
Yes, in the project we used loglevel as the logger, but I guess people ignored it and were using console.

**Comment by zo-chu** [comment]
yeah, it's a common issue, but if the linter will stop commits with console log we will get people to use proper logging (hopefully)

**Comment by Kpoke** [comment]
Just checked, only console.logs in the project are in the migration files and the custom scripts
