### ISSUE TITLE
Chore: Make linter no-unused-vars warning into error and fix the code

### ISSUE THREAD

**Issue by zo-chu** [Greenstand/treetracker-wallet-api#221]
/.eslintrc.json has

```
no-unused-vars: warn
no-unused-expressions: warn
```

the task is to set them all to be "error" instead of warn  and fix the errors by cleaning up the code

**Comment by keyy123** [comment]
@zo-chu, Is this issue ticket still open? I would like to try it!

**Comment by dadiorchen** [comment]
@keyy123 please ignore this
