### ISSUE TITLE
Publish `TokensAssigned` event on token creation and assignment

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/treetracker-wallet-api#228]
Make changes in wallet api service to emit the TokensAssigned event when 

1. tokens are created associating them with a capture_id and with a wallet.
2. transferred from one wallet to another.

The format for the events published is roughly the following. If this requires changes, please discuss with @ZavenArra or @arunbakt .

{
"type": "TokensAssigned",
"wallet_name": "joeswallet",
"entries": [
{ "capture_id": "63e00bca-8eb0-11eb-8dcd-0242ac130003", "token_id": "9d7abad8-8eb0-11eb-8dcd-0242ac130003" },
{ "capture_id": "8533b704-8eb0-11eb-8dcd-0242ac130003", "token_id":"a5799d94-8eb0-11eb-8dcd-0242ac130003" } ]
}

The emitted events should be published as messages to RabbitMQ to an exchange named `wallet-api-ex` and bound to a queue named `wallet-api:events`.

If you want to explore how messages are published to rabbitmq, please take a look at [treetracker-api](https://github.com/Greenstand/treetracker-api) project and see how the configuration is done under the following folder server/infra/messaging.  We use a library called rascal, doc is [here](https://github.com/guidesmiths/rascal).

This issue is related to the following feature requested in webmap-query-service-consumer. Please see [here](https://github.com/Greenstand/webmap-query-service-consumer/issues/5)

**Comment by dadiorchen** [comment]
@arunbakt couple of question:
1. Token isn't created in the wallet API system, right? I don't know where to embed the code to trigger this emit currently.
2. How do you test the code in some case, like, do you mock it? If I run the integration/e2e test, it's actually running the real code, but should I emit the message? Or mock them out? What's your practice on this? I think at least for the integration tests, we should mock it?
3. Do you know how to mock the message queue to avoid executing?

**Comment by arunbakt** [comment]
@dadiorchen, thank you for asking the question. Let me know if we should chat about this explanation below.

1. I understand that creation of token is not currently under treetracker-wallet-api. @ZavenArra might give us direction on this as to how to proceed with that use case. You can just do the code change for token assignments to wallet on a transfer.

2. If you look at the message queue implementation  in treetracker-field-data, the file [domain-event.js](https://github.com/Greenstand/treetracker-field-data/blob/main/server/models/domain-event.js#L66) has a function named dispatch which takes two parameters, one for storing the event raised (`eventRepositoryImpl`), one for publishing it to the rabbit-mq (`publishToTopic`). We could choose to mock the implementation for `publishToTopic` to not include rabbitmq system in our tests (but the db is included, we could choose to mock that as well).

3. By following step 2, we avoid dealing with rabbit-mq totally and no queue is involved. This mocking would similar how we would mock any other object. In other words, we simply don't worry about what happens to the message that is published to a topic.

You could take a look at the following code to understand what this [publishToTopic](https://github.com/Greenstand/treetracker-field-data/blob/main/server/infra/messaging/RabbitMQMessaging.js#L5) implementation does. The `publishToTopic` is actually the function named `publishMessage` in the `RabbitMQMessaging` file.

**Comment by dadiorchen** [comment]
@arunbakt is it possible to just emit the token without the capture_id? Is it possible for you to receive the capture_id in your system when you consuming the message?
For big transactions, it would slow down the transaction to receive all the capture_id from the DB.

**Comment by arunbakt** [comment]
The target system that is consuming the token don't have any access to capture_ids. It is building the data based on these incoming events. If we want true isolation, either web-map-query has to totally rely on the incoming emitted events or use an api to lookup capture_id for each token, which will be even more slower than a db query.   Isn't a token associated to a capture_id already in wallet schema?

**Comment by dadiorchen** [comment]
Just asking, yes, I can emit the capture_id too, just in case that is easy for you to do it on your side. 
Another question: broker.publish(...) will get response by  on("success") asynchronously, right? Then do you think we need to wait for the confirmation from the server? Is it necessary?

**Comment by arunbakt** [comment]
@dadiorchen  Yes, it is async and event based. If you look at the RabbitMQMessaging.js in infra/messaging folder in field-data service you notice I pass a callback that handles a success and another handler for an error. 

I will send you the message queue connection string via slack.

**Comment by Kpoke** [comment]
#216

**Comment by sebastiangaertner** [comment]
@Kpoke this seems totally closed then?
