### ISSUE TITLE
Cleanup code style

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-wallet-api#229]
Run linter and fix code style issues one by one

npm run eslint

**Comment by keyy123** [comment]
@ZavenArra, Is this issue still open? If so, I would like to try it!

**Comment by dadiorchen** [comment]
@keyy123 please ignore this, you are intrested in backend, right? I will add you into our microservice channel, you will find more tasks there

**Comment by Kpoke** [comment]
resolved on the master branch
