### ISSUE TITLE
SQL is exposing to the postman client.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-api#248]
<img width="1440" alt="Screen Shot 2021-07-03 at 3 40 30 PM" src="https://user-images.githubusercontent.com/5744708/124347092-2ea63300-dc15-11eb-913a-434a17827fc2.png">
Need to check the parameter of the response with appropriate error message.

**Comment by Kpoke** [comment]
The solution is to introduce joi uuid validation on all endpoints that have uuid parameters

**Comment by XLPeng57** [comment]
@Kpoke Hi Daniel, I would like to work on this! Can you assign it to me?

**Comment by XLPeng57** [comment]
@Kpoke Hi Daniel, I would like to work on this! Can you assign it to me?
