### ISSUE TITLE
In Postman instructions, bad link to *.yaml

### ISSUE THREAD

**Issue by philnorc** [Greenstand/treetracker-wallet-api#277]
Towards the end of README.md, under the heading "Postman," the first sentence says:
"Can also use Postman to test the API in a more real environment. Import the API spec from here."
 
The word "here" links to https://github.com/Greenstand/treetracker-wallet-api/blob/master/docs/api/spec/treetracker-token-api.yaml

That link leads to a 404 error.

I guess the link should go to one of the *.yaml files in the "deployment/base" folder.
Or maybe /docs/api/postman/*.json

**Comment by Siddhant-K-code** [comment]
I think it should be this => https://github.com/Greenstand/treetracker-wallet-api/blob/master/docs/api/spec/treetracker-token-api-v1-10-3.yaml

**Comment by sebastiangaertner** [comment]
@Kpoke are these tickets still valid. We are using the API more and more and really having issues with documentation and availability of guidance.

**Comment by philnorc** [comment]
@sebastiangaertner, in the fall of '21 I wrote
- [How to Use the Treetracker Wallet API](https://greenstand.org/docs/user-guides/walletapihow.php)
- [Treetracker Wallet API Reference](https://greenstand.org/docs/user-guides/walletapiref.php?notes)

To write that advice I tested thoroughly at 
https://prod-k8s.treetracker.org
The documentation is as accurate as I could make it at the time.

But I also found a lot of issues. I posted a first batch of them to this repo. 
All of them become visible by adding the 
[?notes](https://greenstand.org/docs/user-guides/walletapiref.php?notes) 
switch to the URL of the reference. Then search for the string `???`

Also note that the location https://greenstand.org/docs/ is deprecated. 
Going forward, documentation lives in *.md files in the 
[greenstand-documentation](https://github.com/Greenstand/greenstand-documentation) repo. 
See esp. issue 18 of that repo.
