### ISSUE TITLE
TLS connect error for API server run locally

### ISSUE THREAD

**Issue by philnorc** [Greenstand/treetracker-wallet-api#278]
I cloned the API server to a Linux machine,
operating system Ubuntu 18.

No client could connect to it.
Postman, cURL, and JavaScript all returned the same TLS error:
OpenSSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Other Node.JS servers run on the same machine without issue.
OpenSSL is up to date. 
Node.JS 17, 16, and 12 all generate the same error. 

Solve the problem thus: 
1. Create and trust a self-signed certificate for localhost
2. Edit ./.env to point to the certificate and key files 
3. Edit ./server/server.js to provide an https server

Details follow:

//-----------------------------------
// Create a self-signed certificate for localhost

openssl req -x509 -nodes -subj '/CN=localhost' -newkey rsa:4096 \\
   -keyout sskey.pem -out sscert.pem -sha256 -days 365

// ADD it to /etc/ssl/

/etc/ssl/certs/sscert.pem
/etc/ssl/private/sskey.pem

// GIVE those two files the right permissions, probably:

sudo chown root:root /etc/ssl/certs/sscert.pem
sudo chmod 644 /etc/ssl/private/sskey.pem

//-----------------------------------
// EDIT .env to point to the certificate and key

KEY_FILE='/path/to/sskey.pem'
CERT_FILE='/path/to/sscert.pem'

-------------------------------
// EDIT server/server.js
// COMMENT out the function app.listen 
// ADD an http server, including the certificate files

//app.listen(port,()=>{
//    log.info(`listening on port:${  port}`);
//    log.debug("debug log level!");
//});

const fs=require('fs');
var key=fs.readFileSync(process.env.KEY_FILE); 
var cert=fs.readFileSync(process.env.CERT_FILE);
var certs={'key':key,'cert':cert};
var http=require('https');
var server;
async function startServer(){
  server=http.createServer(certs,app);
  server.listen(port);
}//startServer
startServer();

-------------------------------

**Comment by dadiorchen** [comment]
Using TLS? I'm not familar with the protocol, but I thought we just use simple http protocol with SSL for the server? for the prod env, maybe the server is bihend some proxy which provide SSL

**Comment by philnorc** [comment]
Oops. My mistake. You are right. I did not think to try http. The api server does accept http requests. In production something else--Apache I guess--redirects http to https.
