### ISSUE TITLE
The extra slash in url shouldn't crash the API

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-api#280]
if we try to do POST https://prod-k8s.treetracer.org/wallet//auth  the extra slack (//) will cause an error when request. It is inconvenient and confusing for people.

**Comment by philnorc** [comment]
Ignore the change in the first commit, #057c85a

The API's node.js can redirect request paths //... to /...
with a 7 lines in server/app.js

```
app.use(function(req, res, next) {
  if(req.url.slice(0,2)==="//"){
    res.redirect(308,req.url.slice(1));
    res.send();
  }//if
  else{next();}
});

```
But fixing the API's nodejs server may not solve the problem.
In production, our nodejs is behind an Amazon Envoy proxy server.
And that server may choke on paths that begin //
I don't know how to test.

MORE DETAIL:
It seems Apache and github have no problem with paths that begin //
The following URLs all work:
https://philnorcross.com//robots.txt
https://greenstand.org//devbox
https://github.com//Greenstand

Our production API on Amazon's envoy server does have a problem:
The following return errors:
GET https://prod-k8s.treetracker.org//wallet/wallets?limit=99
POST https://prod-k8s.treetracker.org//auth

The reply headers say:
HTTP/1.1 301 Moved Permanently
location: https://map.treetracker.org//wallet/auth
server: envoy
HTTP/2 403
x-cache: Error from cloudfront

**Comment by Kpoke** [comment]
https://stackoverflow.com/questions/71297515/is-there-a-way-to-remove-double-slash-using-regex-in-ambassador-emissary-ingress 

This is for ambassador. @emmanue 

But I have also included the middleware above in the code
