### ISSUE TITLE
Implement missing end point (Wallet event list)

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-wallet-api#294]
In the collection the following end point exists but its not yet implemented 

{{BASE_URL}}/events?limit=10&since=timestamp&wallet=WalletName

to show all events in a wallet

**Comment by Kpoke** [comment]
Work should be done off of https://github.com/Kpoke/treetracker-wallet-api/tree/fix/refactoring

**Comment by mayankbucha** [comment]
@Kpoke I would  like to work on this.

**Comment by Kpoke** [comment]
@mayankbucha any update on this?

**Comment by mayankbucha** [comment]
@Kpoke sorry I was a bit occupied for last month. This week will try to complete it.

**Comment by Kpoke** [comment]
Sure no problem at all @mayankbucha. You could also work directly off of master, I have updated it

**Comment by sebastiangaertner** [comment]
@mayankbucha did you get anywhere with this?

**Comment by sebastiangaertner** [comment]
![Uploading Screenshot 2023-05-08 at 09.56.59.png…]()

**Comment by Kpoke** [comment]
{{BASE_URL}}/{{wallet_id}}/events

**Comment by Kpoke** [comment]
I think we should have {{BASE_URL}}/{{wallet_id}}/events, 
It should support limit and offsets, and should also support filtering by dates (before and after). 
Also there is a concept of wallets and managed wallets, basically a wallet can be in control of other wallets. A wallet should only be able to get events of its own wallet or its managed wallets

**Comment by joonaun93** [comment]
Hi, Edmund here. I can take a crack at this issue.

**Comment by Kpoke** [comment]
what events do we want to return, just the transfers? @sebastiangaertner
