### ISSUE TITLE
new endpoint /wallets/uuid should provide a getWalletInfo response

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-wallet-api#295]
Get Info should provide all details of one wallet only including a total Number of tokens.

**Comment by Kpoke** [comment]
Work should be done off of https://github.com/Kpoke/treetracker-wallet-api/tree/fix/refactoring

**Comment by sebastiangaertner** [comment]
@Kpoke any news on this ? Is there a chance to get it added to production since it is a basic request needed fro the iOS app dev that is happening.

**Comment by Kpoke** [comment]
I'm yet to work on this but I will get it done ASAP. Is the goal to get it to dev environment or does it have to be in production? @sebastiangaertner

**Comment by dadiorchen** [comment]
The difficulty now is the version management, so @Kpoke your work is based on master right? so if that's true, then the release of the newest code will impact the current clients, there are some new features like claim, are bound to the master, and maybe some API spec change

**Comment by dadiorchen** [comment]
I'm working on a proposal for version control and management, let's get this problem involved and find a good solution.

**Comment by sebastiangaertner** [comment]
ok. I can not quite understand how that changes the timeline. @Kpoke bringing it into dev first would be great since @AlexCornforth works on this through the dev environment.
