### ISSUE TITLE
/transfers/:transfer_id/tokens endpoint does not work

### ISSUE THREAD

**Issue by PH-Eagle** [Greenstand/treetracker-wallet-api#296]
uuid isn't actually parsed as string for the SQL request, and also the function above that tries to iterate over the result rather than result.rows.

**Comment by dadiorchen** [comment]
You mean can not query uuid by the string directly? But I remember I can successfully query by ` id ='some-uuid'` directly?

**Comment by PH-Eagle** [comment]
If I literally do a `GET` call for `/transfer/xxx.../tokens` (with the xxx... being a valid and existing UUID) on the current master branch, it will throw a 500 error with an SQL error message. Example:

{"code":500,"message":"Unknown error (\n      SELECT \"token\".* FROM \"token\"\n      JOIN \"transaction\" \n      ON \"token\".id = \"transaction\".token_id\n      WHERE \"transaction\".transfer_id = deb0c8f8-01ad-4e2d-b02c-225ee07dd863\n      LIMIT 10\n      OFFSET 0 - syntax error at or near \"ad\")"}

The issue is that in `tokenRepository.js`, the `getByTransferId` function doesn't have single quotes around the input so it's not parsed as a string. In addition, in the tokenService, the calling function tries to iterate over `result` rather than `result.rows`, which also doesn't work as far as I can tell.

**Comment by dadiorchen** [comment]
@PH-Eagle oh, that make sense, seems we missed tests to cover this endpoint, could you open a PR for fixing?

**Comment by dadiorchen** [comment]
Thank you! please fork this branch: https://github.com/Greenstand/treetracker-wallet-api/tree/v1.10

**Comment by PH-Eagle** [comment]
https://github.com/Greenstand/treetracker-wallet-api/pull/297

**Comment by sebastiangaertner** [comment]
Thanks Paul for finding and fixing this. We will roll it out by the 14th of September.
