### ISSUE TITLE
Create /tokens routes in wallets API

### ISSUE THREAD

**Issue by mzyau** [Greenstand/treetracker-wallet-api#31]
Create tokens routes along with unit and integration testing based on latest API specs.

<img width="626" alt="Screen Shot 2020-09-25 at 2 05 33 PM" src="https://user-images.githubusercontent.com/46699214/94301231-37583300-ff38-11ea-89ec-37699a23f66e.png">

**Comment by dadiorchen** [comment]
@mzyau because I need to write the integration test for transfer, I have added a token API in the router, but it is far away from complete, please feel free to change my current code on this.
