### ISSUE TITLE
Create /wallets routes in wallets API

### ISSUE THREAD

**Issue by mzyau** [Greenstand/treetracker-wallet-api#32]
Create /wallets routes along with unit and integration testing based on latest API specs. (Similar to the old API's /accounts routes that will be replaced)

<img width="627" alt="Screen Shot 2020-09-25 at 2 06 52 PM" src="https://user-images.githubusercontent.com/46699214/94301339-65d60e00-ff38-11ea-951c-29b7249fce20.png">

**Comment by zo-chu** [comment]
@mzyau I would like to work on this one =)
