### ISSUE TITLE
Paginated 'get all trees' endpoint

### ISSUE THREAD

**Issue by crbertoldo** [Greenstand/treetracker-wallet-api#332]
Captures data can be individually retrieved via the `/webmap/tree?uuid=<uuid-got-from-wallet>` endpoint. Given a big capture amount and basic performance requirements, is desired to have a way to retrieve such data in a batch, perhaps through a new endpoint (e.g., `webmap/trees`) that may receive paras limited `page`, `limit`, `start`, etc. for proper pagination.

Note: through the admin panel, per the image below, we have a 20k entries limitation, and the `uuid` seems to be unavailable:

![Screen Shot 2022-10-28 at 10 10 03](https://user-images.githubusercontent.com/6054708/200709466-31cebe0c-6d52-4292-9c8b-a3d088225549.png)

**Comment by sebastiangaertner** [comment]
This has been a known enhancement that is needed in poduction. @dadiorchen or @Kpoke  is this already addressed in the v2 ? Will we provide that off the wallet API or the Treetracker API that is the question or?

**Comment by Kpoke** [comment]
We could
1. wait until Keycloak is fully integrated and make use of the treetracker-api
2. make use of the wallet-api which would make an internal call to the treetracker-api but we would have to associate the wallet API keys with the corresponding organization @sebastiangaertner

**Comment by dadiorchen** [comment]
This has been provided by query api: https://github.com/Greenstand/treetracker-query-api/blob/d5bc51057996bd67d54cc0d11da339f45498f91d/docs/api/spec/query-api.yaml#L31
