### ISSUE TITLE
knex-mock can not work correctly

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-api#36]
Currently, we are using knex-mock to mock the knex, now we can use it to mock the db without problem, the problem is: once we mocked it, we can not UNMOCK it correctly. So, it would lead to test after the DB test (mocked) fail, it's because the previous DB tests break the real knex DB object.

How to reproduce the problem: modify the npm command:
```
    "testWatch": "NODE_ENV=test mocha --timeout 10000 --require co-mocha -w -b --ignore './server/repositories/**/*.spec.js'  './server/**/*.spec.js' './__tests__/supertest.js'"
```

to

```
    "testWatch": "NODE_ENV=test mocha --timeout 10000 --require co-mocha -w -b  './server/**/*.spec.js' './__tests__/supertest.js'"
```

Actually, just because of the problem, we must ignore the repository tests, they would affect others.

**Comment by deepwinter** [comment]
const mockDb = require('mock-knex');
mockDb.mock(Database.getKnex()) 

then later..
mockDb.unmock(Database.getKnex())

I use this mock/unmock in my unit tests and it's fine.  Do you see some other problem?

**Comment by dadiorchen** [comment]
Thanks, Zaven, yes, my unit tests works well, the problem is, after the unit test, if I run the integration test in the same process, then the tests will fail, because the DB object can not unmock correctly, I guess.

![image](https://user-images.githubusercontent.com/5744708/94325085-56ee6a80-ffcf-11ea-86ed-9b2f2ab9220c.png)

**Comment by deepwinter** [comment]
How are you unmocking?

**Comment by dadiorchen** [comment]
![image](https://user-images.githubusercontent.com/5744708/94325188-c6645a00-ffcf-11ea-9c76-caa98cd602ee.png)
The var 'knex' here bings a little confusion, it's not `require('knex')`, it's `require('kenx')({client:'pg'...`

**Comment by deepwinter** [comment]
one thing I notice is that you can just do mock and unmock in before() and after(), that than in beforeEach() afterEach(). 

I also don't uninstall the tracker, and everything is working.  Try it??


  before( function(done) {
    mockDb.mock(Database.getKnex())
    tracker.install();
    done()
  });

  after( function(done) {
    mockDb.unmock(Database.getKnex())
    done()
  });
