### ISSUE TITLE
[ERROR] The server does not support SSL connections

### ISSUE THREAD

**Issue by Harshalyadav** [Greenstand/treetracker-wallet-api#367]
# Description
I Ran **db-migrate --env dev up** command and I got this error.
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: The server does not support SSL connections

**Comment by Kpoke** [comment]
@Harshalyadav I assume you are running this with a local database, in that case the error is correct. In that case you should add a /false at the end of the DATABASE_URL string like below

postgres://test:test@localhost/test?false
