### ISSUE TITLE
Update "/wallets" endpoint

### ISSUE THREAD

**Issue by OlhaD** [Greenstand/treetracker-wallet-api#371]
1) Add 'name' parameter into the request. It is needed for filtering wallets (for example, in autocomplete dropdown).
2) Add 'total' field into the response. It is needed to perform server-side pagination (for example, in an autocomplete dropdown with server-side pagination and in a table pagination).

**Comment by OlhaD** [comment]
@dadiorchen As discussed in the last 'Wallet Admin Client' meeting, we need to update an API with these changes. I did not find a relevant issue for it so I created this one. Could you please assign it to me?

**Comment by pranavkparti** [comment]
This issue seems to be resolved.
