### ISSUE TITLE
/transfers endpoint doesn't return some parameters

### ISSUE THREAD

**Issue by pranavkparti** [Greenstand/treetracker-wallet-api#385]
The `/transfers` endpoint needs to return `limit`, `offset/start`, and `count` parameters to help with pagination on the front end, specifically the 'My Transfers' page on `treetracker-wallet-admin-client`. See [this issue](https://github.com/Greenstand/treetracker-wallet-admin-client/issues/48) for reference.

**Comment by OlhaD** [comment]
@pranavkparti are you sure you need limit and offset/start values in the API's return? I think an API should accept it as parameters and return the count.

**Comment by pranavkparti** [comment]
@OlhaD  The microservices (like query, reporting etc.) return the limit and offset parameters as well. It may be good to keep in line with that. But only the total count is fully necessary.

**Comment by OlhaD** [comment]
@Kpoke please, assign this issue to @pranavkparti. PR is ready and attached to the issue.
