### ISSUE TITLE
My Transfers V1: Ordering by default by Created date (Api change)

### ISSUE THREAD

**Issue by stvgreen1** [Greenstand/treetracker-wallet-api#391]
My Transfers V1: Ordering by default by Created date (Api change)

**Comment by XLPeng57** [comment]
Hi @Kpoke, I can take this! Can I be assigned to this issue?

**Comment by pranavkparti** [comment]
@OlhaD  Does this need to happen on the backend? It may be better to have a `sort_by` query parameter instead that we can call by default on the frontend.

**Comment by OlhaD** [comment]
@pranavkparti both will work for now. Adding a 'sort_by' parameter is preferable because we will have more sorting fields in the near future. Am I right that the backend does not support this field at the moment?

**Comment by pranavkparti** [comment]
This issue has been resolved.
