### ISSUE TITLE
Filtering by `before` in `GET /transfers` doesn't include current day

### ISSUE THREAD

**Issue by pranavkparti** [Greenstand/treetracker-wallet-api#401]
The query parameter `before` returns all transfers before the current day.
It needs to also include transfers occurring on the current day.

This issue needs to be fixed for the v1 release of `treetracker-wallet-admin-client`, specifically for the My Transfers page.

**Comment by AnthonyJHizon** [comment]
Would incrementing the date by a day in either the api call or in the api itself be a good fix?

**Comment by pranavkparti** [comment]
@Kpoke Can you assign me to this please?

**Comment by Kpoke** [comment]
Don't think this is an issue. It depends on the value been sent as the before parameter https://github.com/Greenstand/treetracker-wallet-api/blob/c1275345e49465d0e2a38a209f0d53a3466fc6db/server/repositories/BaseRepository.js#L53-L58
