### ISSUE TITLE
Fix the github action problem

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-api#478]
This might be related to github action infra or node.js runtime env problem.

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/826c0ccd-0542-451c-b0bc-2d8f4d69163f">
https://github.com/Greenstand/treetracker-wallet-api/actions/runs/10162864780/job/28104424958

**Comment by agnish7** [comment]
Feel free to assign it to me
